---
title: "Project 1 DS6371"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Libaries
library(dplyr)
library(ggplot2)
library(car)
library(caret)
library(scales)
library(tidyr)
library(readr)
library(purrr)
library(forcats)
library(imputeMissings)
library(tidyverse)
library(leaps)
library(MASS)
library(olsrr)
library(asbio)
library(DAAG)
```




```{r}
#read in data 
train <- read.csv("train.csv")
test <- read.csv("test.csv")
```


```{r}
#Select data

neighborhoodDatTrain <- dplyr::filter(train,Neighborhood =="Edwards" | Neighborhood =="NAmes" | Neighborhood == "BrkSide")
neighborhoodDatTrain <- neighborhoodDatTrain[,c(13,47,81)]


neighborhoodDatTest <- dplyr::filter(test,Neighborhood =="Edwards" | Neighborhood =="NAmes" | Neighborhood == "BrkSide")
neighborhoodDatTest <- neighborhoodDatTest[,c(13,47)]

neighborhoodDatTrain$Neighborhood <- as.factor(neighborhoodDatTrain$Neighborhood)




```





```{r}

#Some summary statistics on training data set
summary(train)

#Some summary statistics on training data set
summary(test)


#Some EDA on the training 


# Basic histogram of prices
p<-ggplot(neighborhoodDatTrain, aes(x=SalePrice)) + geom_histogram(color="black", fill="white")
p

# Basic histogram of sq footage
q<-ggplot(neighborhoodDatTrain, aes(x=GrLivArea)) + geom_histogram(color="black", fill="white")
q

# Bar plot of neighborhoods
ggplot(neighborhoodDatTrain) + geom_bar(aes(x = Neighborhood))

#Scatter plots
r <-ggplot(neighborhoodDatTrain, aes(x = (GrLivArea), y = (SalePrice),color=Neighborhood)) +
    geom_point()
r

################################################################################
#Log transform

# Basic histogram of prices
p<-ggplot(neighborhoodDatTrain, aes(x=log(SalePrice))) + geom_histogram(color="black", fill="white")
p

# Basic histogram of sq footage
q<-ggplot(neighborhoodDatTrain, aes(x=log(GrLivArea))) + geom_histogram(color="black", fill="white")
q

#Scatter plots
r <-ggplot(neighborhoodDatTrain, aes(x = log(GrLivArea), y = log(SalePrice),color=Neighborhood)) +
    geom_point()
r

################################################################################
#Create lm with outliers
priceLm <- lm(log(SalePrice)~log(GrLivArea)+Neighborhood+Neighborhood*GrLivArea,data=neighborhoodDatTrain)
summary(priceLm)
confint(priceLm)

#Look at ANOVA
res.aov <- aov(log(SalePrice)~log(GrLivArea)+Neighborhood+Neighborhood*GrLivArea, data = neighborhoodDatTrain)
summary(res.aov)

plot(priceLm)


#Model diagnostics, leverage plots
#leveragePlots(lm(log(SalePrice)~log(GrLivArea)+Neighborhood+Neighborhood*GrLivArea,data=neighborhoodDatTrain))

#Model diagnostics, Cook's Distance
#plot(cooks.distance(lm(log(SalePrice)~log(GrLivArea)+Neighborhood+Neighborhood*GrLivArea,data=neighborhoodDatTrain)))


#sort(cooks.distance(lm(log(SalePrice)~log(GrLivArea)+Neighborhood+Neighborhood*GrLivArea,data=neighborhoodDatTrain)),decreasing = TRUE)



#Model diagnostics, Quantile-Quantile plot
qqPlot(log(neighborhoodDatTrain$SalePrice))


#Hist of residuals
h <- hist(priceLm$residuals, breaks = 10, density = 10,col = "lightgray",main = "Residuals") 
xfit <- seq(min(priceLm$residuals), max(priceLm$residuals), length = 40) 
yfit <- dnorm(xfit, mean = mean(priceLm$residuals), sd = sd(priceLm$residuals)) 
yfit <- yfit * diff(h$mids[1:2]) * length(priceLm$residuals) 


################################################################################
#Create lm without outliers
noOutlierDat <- neighborhoodDatTrain[-c(169,190,339),]
priceLm <- lm(log(SalePrice)~log(GrLivArea)+Neighborhood+Neighborhood*GrLivArea,data=noOutlierDat)
summary(priceLm)
confint(priceLm)

#Internal CV
trainIndex <- createDataPartition(neighborhoodDatTrain$SalePrice, p = .8, list = FALSE, times = 1)
head(trainIndex)

saleTrain <- neighborhoodDatTrain[ trainIndex,]
saleTest  <- neighborhoodDatTrain[-trainIndex,]

pred.w.plim <- predict(lm(log(SalePrice)~log(GrLivArea)+Neighborhood+Neighborhood*GrLivArea,data=saleTrain), saleTest, interval = "prediction")
pred.w.clim <- predict(lm(log(SalePrice)~log(GrLivArea)+Neighborhood+Neighborhood*GrLivArea,data=saleTrain), saleTest, interval = "confidence")
#View(exp(pred.w.plim))

matplot(saleTest$SalePrice, cbind(pred.w.clim, pred.w.plim[,-1]),
        lty = c(1,2,2,3,3), type = "l", ylab = "predicted y")



#predict test data set
pred.w.plim <- predict(priceLm, neighborhoodDatTest, interval = "prediction")
#View(exp(pred.w.plim))
#View(neighborhoodDatTrain$SalePrice)


#Look at ANOVA
res.aov <- aov(log(SalePrice)~log(GrLivArea)+Neighborhood+Neighborhood*GrLivArea, data = noOutlierDat)
summary(res.aov)

plot(priceLm)


#Model diagnostics, leverage plots
#leveragePlots(lm(log(SalePrice)~log(GrLivArea)+Neighborhood+Neighborhood*GrLivArea,data=noOutlierDat))

#Model diagnostics, Cook's Distance
#plot(cooks.distance(lm(log(SalePrice)~log(GrLivArea)+Neighborhood+Neighborhood*GrLivArea,data=noOutlierDat)))


#sort(cooks.distance(lm(log(SalePrice)~log(GrLivArea)+Neighborhood+Neighborhood*GrLivArea,data=noOutlierDat)),decreasing = TRUE)



#Model diagnostics, Quantile-Quantile plot
qqPlot(log(noOutlierDat$SalePrice))


#Hist of residuals
h <- hist(priceLm$residuals, breaks = 10, density = 10,col = "lightgray",main = "Residuals") 
xfit <- seq(min(priceLm$residuals), max(priceLm$residuals), length = 40) 
yfit <- dnorm(xfit, mean = mean(priceLm$residuals), sd = sd(priceLm$residuals)) 
yfit <- yfit * diff(h$mids[1:2]) * length(priceLm$residuals) 






CVdat <- CVlm(data = neighborhoodDatTrain, form.lm = formula(log(SalePrice)~log(GrLivArea)+Neighborhood+Neighborhood*GrLivArea),
              m = 3, dots = FALSE, seed = 29, plotit = c("Observed","Residual"),
              main="Small symbols show cross-validation predicted values",
              legend.pos="topleft", printit = TRUE)
CVdat

(press(priceLm))

```

```{r}
####Analysis 2####

#read in data

analysis2Train <- read.csv("train.csv")
test <- read.csv("test.csv")



```

```{r}

#Look at outcome variable
ggplot(data = analysis2Train %>% filter(!is.na(log(SalePrice)))) +
  geom_histogram(aes(x = log(SalePrice)), fill = "red", alpha = 1/2, binwidth = 0.01) +
  scale_x_continuous(labels = dollar_format()) +
  labs(
    title = "Outcome Sale Price, right skew"
  ) +
  theme(
    plot.title = element_text(hjust = 0.5, size = 15, face = "bold"), 
  )

#Look at missing data
na_prop <- analysis2Train %>% 
  dplyr::select(-SalePrice) %>% 
  map(is.na) %>% 
  map_dfr(mean) %>%
  pivot_longer(cols = everything(), names_to = "variables", values_to = "prop") %>% 
  filter(prop > 0) %>% 
  arrange(desc(prop))

na_prop %>%
  ggplot(aes(x = fct_reorder(variables, prop), y = prop, fill = variables)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  theme(legend.position = "none") +
  labs(
    x = "Explanatory variables",
    y = "The proportions of NA values per column"
  ) +
  scale_y_continuous(breaks = seq(0, 1, by = 0.1)) +
  theme(axis.text.y = element_text(size = 10))

analysis2Train$PoolQC[is.na(analysis2Train$PoolQC)] <- "None"
analysis2Train$MiscFeature[is.na(analysis2Train$MiscFeature)] <- "None"
analysis2Train$Alley[is.na(analysis2Train$Alley)] <- "No"
analysis2Train$Fence[is.na(analysis2Train$Fence)] <- "No"
analysis2Train$FireplaceQu[is.na(analysis2Train$FireplaceQu)] <- "No"
analysis2Train$GarageType[is.na(analysis2Train$GarageType)] <- "No"
analysis2Train$GarageFinish[is.na(analysis2Train$GarageFinish)] <- "No"
analysis2Train$GarageQual[is.na(analysis2Train$GarageQual)] <- "No"
analysis2Train$GarageCond[is.na(analysis2Train$GarageCond)] <- "No"
analysis2Train$BsmtExposure[is.na(analysis2Train$BsmtExposure)] <- "NoBs"
analysis2Train$BsmtCond[is.na(analysis2Train$BsmtCond)] <- "NoBs"
analysis2Train$BsmtQual[is.na(analysis2Train$BsmtQual)] <- "NoBs"
analysis2Train$BsmtFinType1[is.na(analysis2Train$BsmtFinType1)] <- "NoBs"
analysis2Train$BsmtFinType2[is.na(analysis2Train$BsmtFinType2)] <- "NoBs"

# To specify the levels of ordered factors
PoolQC_lev <- c("None", "Fa", "TA", "Gd", "Ex")
Fence_lev <- c("No", "MnWw", "GdWo", "MnPrv", "GdPrv")
FireplaceQu_lev <- c("No", "Po", "Fa", "TA", "Gd", "Ex")
GarageFinish_lev <- c("No", "Unf", "RFn", "Fin")
GarageQual_lev <- c("No", "Po", "Fa", "TA", "Gd", "Ex")
GarageCond_lev <- c("No", "Po", "Fa", "TA", "Gd", "Ex")
BsmtExposure_lev <- c("NoBs", "No", "Mn", "Av", "Gd")
BsmtCond_lev <- c("NoBs", "Po", "Fa", "TA", "Gd", "Ex")
BsmtQual_lev <- c("NoBs", "Po", "Fa", "TA", "Gd", "Ex")
BsmtFinType1_lev <- c("NoBs", "Unf", "LwQ", "Rec", "BLQ", "ALQ", "GLQ")
BsmtFinType2_lev <- c("NoBs", "Unf", "LwQ", "Rec", "BLQ", "ALQ", "GLQ")

analysis2Train2 <- analysis2Train %>%
  mutate(PoolQC = parse_factor(PoolQC, levels = PoolQC_lev, ordered = TRUE),
         MiscFeature = parse_factor(MiscFeature),
         Alley = parse_factor(Alley),
         Fence = parse_factor(Fence, levels = Fence_lev, ordered = TRUE),
         FireplaceQu = parse_factor(FireplaceQu, levels = FireplaceQu_lev, ordered = TRUE),
         GarageType = parse_factor(GarageType),
         GarageFinish = parse_factor(GarageFinish, levels = GarageFinish_lev, ordered = TRUE),
         GarageQual = parse_factor(GarageQual, levels = GarageQual_lev, ordered = TRUE),
         GarageCond = parse_factor(GarageCond, levels = GarageCond_lev, ordered = TRUE),
         BsmtExposure = parse_factor(BsmtExposure, levels = BsmtExposure_lev, ordered = TRUE),
         BsmtCond = parse_factor(BsmtCond, levels = BsmtCond_lev, ordered = TRUE),
         BsmtQual = parse_factor(BsmtQual, levels = BsmtQual_lev, ordered = TRUE),
         BsmtFinType1 = parse_factor(BsmtFinType1, levels = BsmtFinType1_lev, ordered = TRUE),
         BsmtFinType2 = parse_factor(BsmtFinType2, levels = BsmtFinType2_lev, ordered = TRUE))


#lets impute some data
#Col 4 lot frontage
analysis2Train2[,4][is.na(analysis2Train2[,4])] <- round(mean(analysis2Train2[,4], na.rm = TRUE))

#Col 27, massvnr
analysis2Train2[,27][is.na(analysis2Train2[,27])] <- round(mean(analysis2Train2[,27], na.rm = TRUE))

#Col 60, Garage year built
analysis2Train2[,60][is.na(analysis2Train2[,60])] <- round(mean(analysis2Train2[,60], na.rm = TRUE))

#Col 26, MasVnrType
analysis2Train2$MasVnrType <- analysis2Train2$MasVnrType %>% tidyr::replace_na("Stone")

#Col 43, electrical
analysis2Train2$Electrical <- analysis2Train2$Electrical %>% tidyr::replace_na("SBrkr ")

analysis2Train2$GrLivArea <- log(analysis2Train2$GrLivArea)


#sort(is.na(analysis2Train2),decreasing = TRUE)

#analysis2Train2[!complete.cases(analysis2Train2),]




################################################################################
#test dat
#Look at missing data
na_prop <- test %>% 
 
  map(is.na) %>% 
  map_dfr(mean) %>%
  pivot_longer(cols = everything(), names_to = "variables", values_to = "prop") %>% 
  filter(prop > 0) %>% 
  arrange(desc(prop))

na_prop %>%
  ggplot(aes(x = fct_reorder(variables, prop), y = prop, fill = variables)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  theme(legend.position = "none") +
  labs(
    x = "Explanatory variables",
    y = "The proportions of NA values per column"
  ) +
  scale_y_continuous(breaks = seq(0, 1, by = 0.1)) +
  theme(axis.text.y = element_text(size = 10))

test$PoolQC[is.na(test$PoolQC)] <- "None"
test$MiscFeature[is.na(test$MiscFeature)] <- "None"
test$Alley[is.na(test$Alley)] <- "No"
test$Fence[is.na(test$Fence)] <- "No"
test$FireplaceQu[is.na(test$FireplaceQu)] <- "No"
test$GarageType[is.na(test$GarageType)] <- "No"
test$GarageFinish[is.na(test$GarageFinish)] <- "No"
test$GarageQual[is.na(test$GarageQual)] <- "No"
test$GarageCond[is.na(test$GarageCond)] <- "No"
test$BsmtExposure[is.na(test$BsmtExposure)] <- "NoBs"
test$BsmtCond[is.na(test$BsmtCond)] <- "NoBs"
test$BsmtQual[is.na(test$BsmtQual)] <- "NoBs"
test$BsmtFinType1[is.na(test$BsmtFinType1)] <- "NoBs"
test$BsmtFinType2[is.na(test$BsmtFinType2)] <- "NoBs"

# To specify the levels of ordered factors
PoolQC_lev <- c("None", "Fa", "TA", "Gd", "Ex")
Fence_lev <- c("No", "MnWw", "GdWo", "MnPrv", "GdPrv")
FireplaceQu_lev <- c("No", "Po", "Fa", "TA", "Gd", "Ex")
GarageFinish_lev <- c("No", "Unf", "RFn", "Fin")
GarageQual_lev <- c("No", "Po", "Fa", "TA", "Gd", "Ex")
GarageCond_lev <- c("No", "Po", "Fa", "TA", "Gd", "Ex")
BsmtExposure_lev <- c("NoBs", "No", "Mn", "Av", "Gd")
BsmtCond_lev <- c("NoBs", "Po", "Fa", "TA", "Gd", "Ex")
BsmtQual_lev <- c("NoBs", "Po", "Fa", "TA", "Gd", "Ex")
BsmtFinType1_lev <- c("NoBs", "Unf", "LwQ", "Rec", "BLQ", "ALQ", "GLQ")
BsmtFinType2_lev <- c("NoBs", "Unf", "LwQ", "Rec", "BLQ", "ALQ", "GLQ")

test2 <- test %>%
  mutate(PoolQC = parse_factor(PoolQC, levels = PoolQC_lev, ordered = TRUE),
         MiscFeature = parse_factor(MiscFeature),
         Alley = parse_factor(Alley),
         Fence = parse_factor(Fence, levels = Fence_lev, ordered = TRUE),
         FireplaceQu = parse_factor(FireplaceQu, levels = FireplaceQu_lev, ordered = TRUE),
         GarageType = parse_factor(GarageType),
         GarageFinish = parse_factor(GarageFinish, levels = GarageFinish_lev, ordered = TRUE),
         GarageQual = parse_factor(GarageQual, levels = GarageQual_lev, ordered = TRUE),
         GarageCond = parse_factor(GarageCond, levels = GarageCond_lev, ordered = TRUE),
         BsmtExposure = parse_factor(BsmtExposure, levels = BsmtExposure_lev, ordered = TRUE),
         BsmtCond = parse_factor(BsmtCond, levels = BsmtCond_lev, ordered = TRUE),
         BsmtQual = parse_factor(BsmtQual, levels = BsmtQual_lev, ordered = TRUE),
         BsmtFinType1 = parse_factor(BsmtFinType1, levels = BsmtFinType1_lev, ordered = TRUE),
         BsmtFinType2 = parse_factor(BsmtFinType2, levels = BsmtFinType2_lev, ordered = TRUE))


#lets impute some data
#Col 4 lot frontage
test2[,4][is.na(test2[,4])] <- round(mean(test2[,4], na.rm = TRUE))

#Col 27, massvnr
test2[,27][is.na(test2[,27])] <- round(mean(test2[,27], na.rm = TRUE))

#Col 60, Garage year built
test2[,60][is.na(test2[,60])] <- round(mean(test2[,60], na.rm = TRUE))

#Col 26, MasVnrType
test2$MasVnrType <- test2$MasVnrType %>% tidyr::replace_na("Stone")

#Col 43, electrical
test2$Electrical <- test2$Electrical %>% tidyr::replace_na("SBrkr ")

test2$GrLivArea <- log(test2$GrLivArea)






```


```{r}
####Build Models####

#Full model
full.model <- lm(log(SalePrice)~.,data = analysis2Train2)

#Stepwise model
step.model <- stepAIC(full.model,direction = "both",trace = FALSE)
#Get model summary


step.model$pred

models <- regsubsets(log(SalePrice)~., data = analysis2Train2, nvmax = 1,
                     method = "seqrep")
summary(models)

#Set seed for reproducibility
set.seed(123)
# Set up repeated k-fold cross-validation
train.control <- trainControl(method = "cv", number = 10)
# Train the model
step.model <- train(log(SalePrice) ~., data = analysis2Train2,
                    method = "leapBackward", 
                    tuneGrid = data.frame(nvmax = 1:75),
                    trControl = train.control
                    )
step.model$results


step.model$bestTune

stepLm <- lm(log(SalePrice)~OverallQual+OverallCond+YearBuilt+BsmtFinType2+KitchenAbvGr+GarageCond,data = analysis2Train2)
summary(stepLm)

summary(step.model$finalModel)
coef(step.model$finalModel, 6)

press(stepLm)

plot(stepLm)

#Model diagnostics, leverage plots
#leveragePlots(stepLm,data=analysis2Train2)

#Model diagnostics, Cook's Distance
#plot(cooks.distance(stepLm,data=analysis2Train2))






##########################################################################


 min.model = lm(log(SalePrice) ~ 1, data=analysis2Train2)
 biggest <- formula(lm(log(SalePrice)~.,analysis2Train2))
 biggest
 
 
fwd.model = step(min.model, direction='forward', scope=biggest)




summary(fwd.model)


forwardlm <- lm(log(SalePrice)~GrLivArea+Neighborhood+GarageCars+OverallCond+HouseStyle+YearBuilt+RoofMatl+BsmtFinSF1+MSZoning+Functional+Condition1+SaleCondition+KitchenQual+LotArea+Condition1+Exterior1st+ScreenPorch+Heating+LandSlope+WoodDeckSF+TotalBsmtSF+LotConfig+CentralAir+GarageQual+BsmtFullBath+Fireplaces+X2ndFlrSF+YearRemodAdd+GarageArea+Foundation+LotFrontage+KitchenAbvGr+GarageCond+SaleType+ExterCond+Street+HalfBath,data = analysis2Train2)


summary(forwardlm)
plot(forwardlm)
#Model diagnostics, leverage plots
#leveragePlots(forwardlm,data=analysis2Train2)

#Model diagnostics, Cook's Distance
#plot(cooks.distance(forwardlm,data=analysis2Train2))



#predict test data set
forward.lm.plim <- predict(forwardlm, test2, interval = "prediction")


####Write forward model
forward.lm.plim <- forward.lm.plim[,1]
forward.lm.plim <- as.data.frame(forward.lm.plim)
forward.lm.plim <- exp(forward.lm.plim[,1])
forward.lm.plim <- forward.lm.plim %>% rename(SalePrice = forward.lm.plim,)
forward.lm.plim[,1][is.na(forward.lm.plim[,1])] <- round(mean(forward.lm.plim[,1], na.rm = TRUE))
out <- write.csv(forward.lm.plim,"forwardModel.csv")



####Write Step model
stepWise.lm.plim <- predict(step.model, test2, interval = "prediction")
stepWise.lm.plim <- exp(stepWise.lm.plim)
stepWise.lm.plim <- as.data.frame(stepWise.lm.plim)
stepWise.lm.plim <- stepWise.lm.plim %>% rename(SalePrice = stepWise.lm.plim,)
stepWise.lm.plim$ID <- seq.int(nrow(stepWise.lm.plim))
outStepwise <- write.csv(stepWise.lm.plim,"stepwiseModel.csv")
#View(stepWise.lm.plim)



# Set seed for reproducibility
set.seed(123)
# Set up repeated k-fold cross-validation
train.control <- trainControl(method = "cv", number = 10)
# Train the model
step.model <- train(log(SalePrice) ~., data = analysis2Train2,
                    method = "leapBackward", 
                    tuneGrid = data.frame(nvmax = 1:10),
                    trControl = train.control
                    )
step.model$results
summary(step.model$finalModel)
coef(step.model$finalModel, 7)

backlm <- lm(log(SalePrice)~OverallQual+OverallCond+YearBuilt+RoofMatl+BsmtFinType2+KitchenAbvGr+GarageCond,data = analysis2Train2)
summary(backlm)

#predict test data set
back.lm.plim <- predict(backlm, test2, interval = "prediction")
back.lm.plim <- back.lm.plim[,1]
back.lm.plim <- exp(back.lm.plim)
back.lm.plim <- as.data.frame(back.lm.plim)
back.lm.plim <- back.lm.plim %>% rename(SalePrice = back.lm.plim,)
back.lm.plim$ID <- seq.int(nrow(back.lm.plim))
outBack <- write.csv(backModel,"backModel1.csv")
#View(back.lm.plim)

#Model diagnostics, leverage plots
#leveragePlots(backlm,data=analysis2Train2)

#Model diagnostics, Cook's Distance
#plot(cooks.distance(backlm,data=analysis2Train2))

#plot(backlm)
#####Custom model####

 customlm <- lm(log(SalePrice)~OverallQual+log(GrLivArea)+Neighborhood+GarageCars+ExterQual+TotalBsmtSF+GarageArea+KitchenQual+YearBuilt,data=analysis2Train2)
 summary(customlm)
 custom.lm.plim <- predict(customlm, test2, interval = "prediction")
 custom.lm.plim <- custom.lm.plim[,1]
 custom.lm.plim <- exp(custom.lm.plim)
 custom.lm.plim <- as.data.frame(custom.lm.plim)
 custom.lm.plim <- custom.lm.plim %>% rename(SalePrice = custom.lm.plim,)
 custom.lm.plim$ID <- seq.int(nrow(custom.lm.plim))
 outCustom <- write.csv(custom.lm.plim,"customModel1.csv")

#Model diagnostics, leverage plots
#leveragePlots(customlm,data=analysis2Train2)

#Model diagnostics, Cook's Distance
#plot(cooks.distance(customlm,data=analysis2Train2))

#plot(customlm)

#View(custom.lm.plim)
```
